//intl action type
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_DUBLICATE_RESET = 'AUTH_DUBLICATE_RESET';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_RESET = 'AUTH_RESET';
export const RESET_TOKEN = 'RESET_TOKEN';

export const UPDATE_UTILITY = 'UPDATE_UTILITY';

export const GET_MASTER_PAGINATION_DATA_START = "GET_MASTER_PAGINATION_DATA_START";
export const GET_MASTER_PAGINATION_DATA_SUCCESS = "GET_MASTER_PAGINATION_DATA_SUCCESS";
export const GET_MASTER_PAGINATION_DATA_FAIL = "GET_MASTER_PAGINATION_DATA_FAIL";
export const RESET_MASTER_PAGINATION_DATA = "RESET_MASTER_PAGINATION_DATA";

export const GET_PATIENT_LOOKUP_DATA_START = "GET_PATIENT_LOOKUP_DATA_START";
export const GET_PATIENT_LOOKUP_DATA_SUCCESS = "GET_PATIENT_LOOKUP_DATA_SUCCESS";
export const GET_PATIENT_LOOKUP_DATA_FAIL = "GET_PATIENT_LOOKUP_DATA_FAIL";

export const GET_BILLING_LOOKUP_DATA_START = "GET_BILLING_LOOKUP_DATA_START";
export const GET_BILLING_LOOKUP_DATA_SUCCESS = "GET_BILLING_LOOKUP_DATA_SUCCESS";
export const GET_BILLING_LOOKUP_DATA_FAIL = "GET_BILLING_LOOKUP_DATA_FAIL";

export const GET_APPOINTMENT_LOOKUP_DATA_START = "GET_APPOINTMENT_LOOKUP_DATA_START";
export const GET_APPOINTMENT_LOOKUP_DATA_SUCCESS = "GET_APPOINTMENT_LOOKUP_DATA_SUCCESS";
export const GET_APPOINTMENT_LOOKUP_DATA_FAIL = "GET_APPOINTMENT_LOOKUP_DATA_FAIL";

export const GET_TREATMENT_PLAN_LOOKUP_DATA_START = "GET_TREATMENT_PLAN_LOOKUP_DATA_START";
export const GET_TREATMENT_PLAN_LOOKUP_DATA_SUCCESS = "GET_TREATMENT_PLAN_LOOKUP_DATA_SUCCESS";
export const GET_TREATMENT_PLAN_LOOKUP_DATA_FAIL = "GET_TREATMENT_PLAN_LOOKUP_DATA_FAIL";

export const GET_STIMULATION_LOOKUP_DATA_START = "GET_STIMULATION_LOOKUP_DATA_START";
export const GET_STIMULATION_LOOKUP_DATA_SUCCESS = "GET_STIMULATION_LOOKUP_DATA_SUCCESS";
export const GET_STIMULATION_LOOKUP_DATA_FAIL = "GET_STIMULATION_LOOKUP_DATA_FAIL";

export const GET_PATIENT_DETAILS_START = "GET_PATIENT_DETAILS_START";
export const GET_PATIENT_DETAILS_SUCCESS = "GET_PATIENT_DETAILS_SUCCESS";
export const GET_PATIENT_DETAILS_FAIL = "GET_PATIENT_DETAILS_FAIL";

export const GET_USER_LOOKUP_DATA_START = "GET_USER_LOOKUP_DATA_START";
export const GET_USER_LOOKUP_DATA_SUCCESS = "GET_USER_LOOKUP_DATA_SUCCESS";
export const GET_USER_LOOKUP_DATA_FAIL = "GET_USER_LOOKUP_DATA_FAIL";

//vitals
export const GET_VITAL_LOOKUP_DATA_START = "GET_VITAL_LOOKUP_DATA_START";
export const GET_VITAL_LOOKUP_DATA_SUCCESS = "GET_VITAL_LOOKUP_DATA_SUCCESS";
export const GET_VITAL_LOOKUP_DATA_FAIL = "GET_VITAL_LOOKUP_DATA_FAIL";

//PRESCRIPTION
export const GET_PRESCRIPTION_LOOKUP_DATA_START = "GET_PRESCRIPTION_LOOKUP_DATA_START";
export const GET_PRESCRIPTION_LOOKUP_DATA_SUCCESS = "GET_PRESCRIPTION_LOOKUP_DATA_SUCCESS";
export const GET_PRESCRIPTION_LOOKUP_DATA_FAIL = "GET_PRESCRIPTION_LOOKUP_DATA_FAIL";

export const GET_ULTRASOUND_LOOKUP_DATA_START = "GET_ULTRASOUND_LOOKUP_DATA_START";
export const GET_ULTRASOUND_LOOKUP_DATA_SUCCESS = "GET_ULTRASOUND_LOOKUP_DATA_SUCCESS";
export const GET_ULTRASOUND_LOOKUP_DATA_FAIL = "GET_ULTRASOUND_LOOKUP_DATA_FAIL";


